/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.baxterplanning.algorithms;

import static org.hamcrest.Matchers.*;
import static org.hamcrest.MatcherAssert.assertThat;

import org.junit.Before;
import org.junit.Test;

public class SortingTest {

  private int[] testArray;

  @Before
  public void beforeMethod() {
    testArray = new int[] {4, 9, 7, 1, 3, 6, 5};
  }

  @Test
  public void whenSelectionSortThenArrayIsSorted() {
    int[] sorted = new int[] {1, 3, 4, 5, 6, 7, 9};
    Sorting.selectionSort(testArray);
    assertThat(testArray, is(sorted));
  }

  @Test
  public void whenMinimumIndexMethodCalledThenMinimumIndexReturned() {
    assertThat(Sorting.getIndexOfMinimumValue(testArray, 0, testArray.length), is(3));
  }

  @Test
  public void whenSwapMethodThenArrayValuesAreSwappedAtGivenIndices() {
    int[] swapped = Sorting.swap(testArray, 2, 5);
    int[] expected = {4, 9, 6, 1, 3, 7, 5};
    assertThat(swapped, is(expected));
  }
}
